version: "3.8"

services:
  api: 
   container_name: money-api
   restart: always
   ports: 
    - 3000:3000
   build:
     dockerfile: ./docker/Dockerfile
     context: ../api
   volumes:
     - ../api:/var/www/app